-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 01:43:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema uresa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uresa` ;

-- -----------------------------------------------------
-- Schema uresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uresa` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `uresa` ;

-- -----------------------------------------------------
-- Table `uresa`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`provincia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`provincia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Localidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Localidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Localidad_provincia1_idx` (`provincia_id` ASC),
  CONSTRAINT `fk_Localidad_provincia1`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `uresa`.`provincia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Empresa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Empresa` (
  `CUIT` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `razon_social` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `Localidad_id` INT NOT NULL,
  PRIMARY KEY (`CUIT`),
  INDEX `fk_Empresa_Localidad1_idx` (`Localidad_id` ASC),
  CONSTRAINT `fk_Empresa_Localidad1`
    FOREIGN KEY (`Localidad_id`)
    REFERENCES `uresa`.`Localidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Establecimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Establecimiento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Establecimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `fecha_carga` DATE NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `archivos_adjuntos` VARCHAR(45) NULL,
  `nro_RNE` VARCHAR(45) NULL,
  `vencimiento_RNE` DATE NULL,
  `nro_factura` INT NULL,
  `Empresa_CUIT` INT NOT NULL,
  `Localidad_id` INT NOT NULL,
  `Categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Establecimiento_Empresa1_idx` (`Empresa_CUIT` ASC),
  INDEX `fk_Establecimiento_Localidad1_idx` (`Localidad_id` ASC),
  INDEX `fk_Establecimiento_Categoria1_idx` (`Categoria_id` ASC),
  CONSTRAINT `fk_Establecimiento_Empresa1`
    FOREIGN KEY (`Empresa_CUIT`)
    REFERENCES `uresa`.`Empresa` (`CUIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Establecimiento_Localidad1`
    FOREIGN KEY (`Localidad_id`)
    REFERENCES `uresa`.`Localidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Establecimiento_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `uresa`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Producto_Alimenticio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Producto_Alimenticio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Producto_Alimenticio` (
  `id` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `nro_factura` INT UNSIGNED NULL,
  `nro_RNPA` INT UNSIGNED NULL,
  `rotulo` LONGTEXT NULL,
  `CAA` VARCHAR(45) NULL,
  `contenido` VARCHAR(45) NULL,
  `denominacion` VARCHAR(45) NULL,
  `fecha_duracion` DATE NULL,
  `marca` VARCHAR(45) NULL,
  `nombre_comercial` VARCHAR(45) NULL,
  `num_y_tipo_reg_marca` VARCHAR(45) NULL,
  `fecha_carga_solicitud` DATE NULL,
  `Controles_y_cuidados` VARCHAR(45) NULL,
  `destino_prod` VARCHAR(45) NULL,
  `forma_uso` VARCHAR(45) NULL,
  `info_adicional` VARCHAR(45) NULL,
  `instrucciones_preparacion` VARCHAR(45) NULL,
  `lugar_venta` VARCHAR(45) NULL,
  `modo_conservacion` VARCHAR(45) NULL,
  `periodo_aptitud` VARCHAR(45) NULL,
  `Vencimiento_RNPA` DATE NULL,
  `ml_nroActa` INT NULL,
  `ml_nroProtocolo` INT NULL,
  `Establecimiento_idEstablecimiento` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_Prod_Alimenticio_UNIQUE` (`id` ASC),
  INDEX `fk_Producto_Alimenticio_Establecimiento1_idx` (`Establecimiento_idEstablecimiento` ASC),
  CONSTRAINT `fk_Producto_Alimenticio_Establecimiento1`
    FOREIGN KEY (`Establecimiento_idEstablecimiento`)
    REFERENCES `uresa`.`Establecimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Material` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Unidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Unidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Envase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Envase` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Envase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NULL,
  `Material_id` INT NOT NULL,
  `Unidad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Envase_Material1_idx` (`Material_id` ASC),
  INDEX `fk_Envase_Unidad1_idx` (`Unidad_id` ASC),
  CONSTRAINT `fk_Envase_Material1`
    FOREIGN KEY (`Material_id`)
    REFERENCES `uresa`.`Material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envase_Unidad1`
    FOREIGN KEY (`Unidad_id`)
    REFERENCES `uresa`.`Unidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`materia_prima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`materia_prima` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`materia_prima` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Rubro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Rubro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Rubro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Establecimiento_has_Rubro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Establecimiento_has_Rubro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Establecimiento_has_Rubro` (
  `Establecimiento_id` INT NOT NULL,
  `Rubro_id` INT NOT NULL,
  PRIMARY KEY (`Establecimiento_id`, `Rubro_id`),
  INDEX `fk_Establecimiento_has_Rubro_Rubro1_idx` (`Rubro_id` ASC),
  INDEX `fk_Establecimiento_has_Rubro_Establecimiento1_idx` (`Establecimiento_id` ASC),
  CONSTRAINT `fk_Establecimiento_has_Rubro_Establecimiento1`
    FOREIGN KEY (`Establecimiento_id`)
    REFERENCES `uresa`.`Establecimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Establecimiento_has_Rubro_Rubro1`
    FOREIGN KEY (`Rubro_id`)
    REFERENCES `uresa`.`Rubro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Producto_Alimenticio_has_Envase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Producto_Alimenticio_has_Envase` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Producto_Alimenticio_has_Envase` (
  `Producto_Alimenticio_id` INT ZEROFILL UNSIGNED NOT NULL,
  `Envase_id` INT NOT NULL,
  PRIMARY KEY (`Producto_Alimenticio_id`, `Envase_id`),
  INDEX `fk_Producto_Alimenticio_has_Envase_Envase1_idx` (`Envase_id` ASC),
  INDEX `fk_Producto_Alimenticio_has_Envase_Producto_Alimenticio1_idx` (`Producto_Alimenticio_id` ASC),
  CONSTRAINT `fk_Producto_Alimenticio_has_Envase_Producto_Alimenticio1`
    FOREIGN KEY (`Producto_Alimenticio_id`)
    REFERENCES `uresa`.`Producto_Alimenticio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Alimenticio_has_Envase_Envase1`
    FOREIGN KEY (`Envase_id`)
    REFERENCES `uresa`.`Envase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uresa`.`Producto_Alimenticio_has_materia_prima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uresa`.`Producto_Alimenticio_has_materia_prima` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uresa`.`Producto_Alimenticio_has_materia_prima` (
  `Producto_Alimenticio_id` INT ZEROFILL UNSIGNED NOT NULL,
  `materia_prima_id` INT NOT NULL,
  `cantidad_mat_prima` INT NOT NULL,
  PRIMARY KEY (`Producto_Alimenticio_id`, `materia_prima_id`),
  INDEX `fk_Producto_Alimenticio_has_materia_prima_materia_prima1_idx` (`materia_prima_id` ASC),
  INDEX `fk_Producto_Alimenticio_has_materia_prima_Producto_Alimenti_idx` (`Producto_Alimenticio_id` ASC),
  CONSTRAINT `fk_Producto_Alimenticio_has_materia_prima_Producto_Alimenticio1`
    FOREIGN KEY (`Producto_Alimenticio_id`)
    REFERENCES `uresa`.`Producto_Alimenticio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Alimenticio_has_materia_prima_materia_prima1`
    FOREIGN KEY (`materia_prima_id`)
    REFERENCES `uresa`.`materia_prima` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
